#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

export RELEASE=1
cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. || exit 1

hash node 2>/dev/null || { echo >&2 "Node not found.  Aborting."; exit 1; }
hash npm 2>/dev/null || { echo >&2 "NPM not found.  Aborting."; exit 1; }

npm install

SHADOW=node_modules/.bin/shadow-cljs

$SHADOW release test
node out/node-tests.js
